### ISSUE TITLE
Zk注册的时候会报错

### ISSUE THREAD

**Issue by liweiyuan** [raomuyang/plum-mesh-agent#8]
![image](https://user-images.githubusercontent.com/26542900/45417709-6125c080-b6b5-11e8-9afd-957bf97ad620.png)
java.lang.IllegalArgumentException: Path must start with / character
应该添加一个"\"的替换逻辑

**Comment by raomuyang** [comment]
@liweiyuan 谢谢提醒，你是对的，开发环境是 macOS/linux，没有注意到windows下的的separator是`\`

**Comment by liweiyuan** [comment]
@Override
    public void createParentNode(String parentNode) throws Exception {
        PathUtils.validatePath(parentNode);
        if (parentNode.equals("/")) return;
        File node = new File(parentNode);
        String parent = node.getParent().trim();
        if (parent.charAt(0) == '\\') {
            parent = parent.replace("\\", "/");
        }
        if (!exists(parent)) {
            createParentNode(parent);
        }
        put(parentNode, DEFAULT_NODE_VALUE);
    }
